# Generated by Django 6.0.4 on 2026-04-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('size', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.URLField()),
            ],
        ),
    ]
